In [1]:
# import modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
# reading the file
dataset = pd.read_csv('newdata.csv')
dataset


Age  Gender  Stream  Internships  CGPA  Hostel  HistoryOfBacklogs  \
0      22       1       0            1     8       1                  1   
1      21       0       1            0     7       1                  1   
2      22       0       2            1     6       0                  0   
3      21       1       2            0     8       0                  1   
4      22       1       3            0     8       1                  0   
...   ...     ...     ...          ...   ...     ...                ...   
2961   23       1       2            0     7       0                  0   
2962   23       1       3            1     7       1                  0   
2963   22       1       2            1     7       0                  0   
2964   22       1       1            1     7       0                  0   
2965   23       1       5            0     8       0                  0   

      PlacedOrNot  
0               1  
1               1  
2               1  
3               1  
4               1  
...           ...  
2961            0  
2962            0  
2963            0  
2964            0  
2965            1  

[2966 rows x 8 columns]

In [4]:
# selecting the features and labels
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

# display dependent variables
Y


array([1, 1, 1, ..., 0, 0, 1], dtype=int64)

In [8]:
# dividing the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.2)

# display dataset
dataset.head()


Age  Gender  Stream  Internships  CGPA  Hostel  HistoryOfBacklogs  \
0   22       1       0            1     8       1                  1   
1   21       0       1            0     7       1                  1   
2   22       0       2            1     6       0                  0   
3   21       1       2            0     8       0                  1   
4   22       1       3            0     8       1                  0   

   PlacedOrNot  
0            1  
1            1  
2            1  
3            1  
4            1

In [9]:
# creating a classifier using sklearn
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0, solver='lbfgs',max_iter=1000).fit(X_train,Y_train)
# printing the acc
clf.score(X_test, Y_test)


0.7491582491582491

In [ ]:
#sample
clf.score([[]])

In [18]:
# predicting for random value
num=clf.predict([[20, 1, 0, 1, 7, 0, 0]])
num[0]

1

In [11]:
# creating a Y_pred for test data
Y_pred = clf.predict(X_test)

# display predicted values
Y_pred


array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,

In [12]:
# evaluation of the classifier
from sklearn.metrics import confusion_matrix, accuracy_score

# display confusion matrix
print(confusion_matrix(Y_test, Y_pred))

# display accuracy
print(accuracy_score(Y_test, Y_pred))


[[180  87]
 [ 62 265]]
0.7491582491582491
